# Generated by Django 4.0.4 on 2022-05-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyStashStore', '0002_subscriber_user_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='fromContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'fromContactForm',
            },
        ),
        migrations.DeleteModel(
            name='subscriber',
        ),
    ]
