# Generated by Django 4.0.4 on 2022-05-12 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xyStashStore', '0003_fromcontactform_delete_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fromcontactform',
            options={'ordering': ('-created',), 'verbose_name_plural': 'fromContactForm'},
        ),
        migrations.AddField(
            model_name='fromcontactform',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
