# Generated by Django 4.0.4 on 2022-05-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyStashStore', '0004_alter_fromcontactform_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fromcontactform',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Contact Form'},
        ),
    ]
