# Generated by Django 4.0.4 on 2022-05-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xyStashStore', '0006_alter_fromcontactform_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
